version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - gradle build
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  type: zip
  files:
    - 'Procfile'
    - 'build/libs/cake-manager-1.0.jar'
  discard-paths: yes