version: 0.1

phases:
  build:
    commands:
      - echo Entered the build phase...
      - gradle build
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - 'build/libs/*.jar'
  discard-paths: yes